# make the namespace match the name you use to instantiate the sensor in the xacro
#my_sensor:
#ForceTorqueSensorInterface:
  #type: hardware_interface/ForceTorqueSensorInterface
  #type: hardware_interface/ForceTorqueSensorHandle
  root: my_sensor_gamma_base
  tip:  my_sensor_gamma_measure
  joints:
  - world_my_sensor_measure_joint
  
